/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class actualizar_producto extends javax.swing.JFrame {

    /**
     * Creates new form actualizar_producto
     */
    public actualizar_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuarioTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ContraTxtField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ISBNTxtField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ISBNTxtField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AutorTxtField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AnioTxtField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AutorTxtField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PrecioTxtField7 = new javax.swing.JTextField();
        RegistrarBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        atrasBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 50, 36, 14);
        jLabel1.getAccessibleContext().setAccessibleName("");

        usuarioTxtField.setText("Usuario");
        getContentPane().add(usuarioTxtField);
        usuarioTxtField.setBounds(80, 70, 207, 20);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 100, 56, 14);

        ContraTxtField1.setText("Contraseña");
        getContentPane().add(ContraTxtField1);
        ContraTxtField1.setBounds(80, 130, 207, 20);

        jLabel3.setText("ISBN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 160, 23, 14);

        ISBNTxtField2.setText("ISBN");
        getContentPane().add(ISBNTxtField2);
        ISBNTxtField2.setBounds(80, 180, 207, 20);

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 210, 37, 14);

        ISBNTxtField3.setText("Nombre");
        getContentPane().add(ISBNTxtField3);
        ISBNTxtField3.setBounds(80, 230, 207, 20);

        jLabel5.setText("Autor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 260, 27, 14);

        AutorTxtField4.setText("Autor");
        getContentPane().add(AutorTxtField4);
        AutorTxtField4.setBounds(80, 280, 207, 20);

        jLabel6.setText("Año");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 300, 19, 14);

        AnioTxtField5.setText("Año");
        getContentPane().add(AnioTxtField5);
        AnioTxtField5.setBounds(80, 320, 207, 20);

        jLabel7.setText("Autor");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 350, 27, 14);

        AutorTxtField6.setText("Autor");
        getContentPane().add(AutorTxtField6);
        AutorTxtField6.setBounds(80, 370, 207, 20);

        jLabel8.setText("Precio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 400, 29, 14);

        PrecioTxtField7.setText("Precio");
        getContentPane().add(PrecioTxtField7);
        PrecioTxtField7.setBounds(80, 420, 207, 20);

        RegistrarBtn.setText("Registrar");
        getContentPane().add(RegistrarBtn);
        RegistrarBtn.setBounds(120, 460, 77, 23);

        jButton1.setText("Actualizar");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 460, 79, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 490, 274, 114);

        atrasBtn.setText("Atrás");
        getContentPane().add(atrasBtn);
        atrasBtn.setBounds(80, 570, 59, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UH.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1609, 0, 86, 91);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UH.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 0, 140, 90);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 460, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizar_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnioTxtField5;
    private javax.swing.JTextField AutorTxtField4;
    private javax.swing.JTextField AutorTxtField6;
    private javax.swing.JTextField ContraTxtField1;
    private javax.swing.JTextField ISBNTxtField2;
    private javax.swing.JTextField ISBNTxtField3;
    private javax.swing.JTextField PrecioTxtField7;
    private javax.swing.JButton RegistrarBtn;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField usuarioTxtField;
    // End of variables declaration//GEN-END:variables
}
