
import Modelos.Product;
import Modelos.RespuestaProduct;
import Servicio.restclient;
import java.awt.Component;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asus
 */
public class consultar_categoria extends javax.swing.JFrame {

    /**
     * Creates new form consultar_producto
     */
    public consultar_categoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Contra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        BuscarBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Respuesta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 92, 36, 14);

        Usuario.setText("Usuario");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario);
        Usuario.setBounds(43, 112, 228, 20);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 138, 56, 14);

        Contra.setText("Contraseña");
        getContentPane().add(Contra);
        Contra.setBounds(43, 158, 228, 20);

        jLabel3.setText("Categoría");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 189, 47, 14);

        Categoria.setText("Categoría");
        getContentPane().add(Categoria);
        Categoria.setBounds(43, 209, 228, 20);

        BuscarBtn.setText("Buscar");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarBtn);
        BuscarBtn.setBounds(122, 247, 65, 23);

        atrasBtn.setText("Atrás");
        getContentPane().add(atrasBtn);
        atrasBtn.setBounds(450, 300, 59, 23);

        Respuesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Respuesta.setColumnSelectionAllowed(true);
        Respuesta.setEditingColumn(1);
        Respuesta.setEditingRow(1);
        Respuesta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Respuesta);
        Respuesta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(302, 92, 452, 196);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UH.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 0, 88, 74);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 533);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
       
        RespuestaProduct<Product> response = null;
		restclient consulta = new restclient();
		try {
			response = consulta.getProduct(Usuario.getText(),Contra.getText(), Categoria.getText());
		} 
                catch (IOException e1) {
            // TODO Auto-generated catch block

		}
		if(response.getCode().equals("200"))
		{
			Product[] nuevo = response.getData();
                        Object [][] a  = new Object[nuevo.length][2];
                        String  b [] = {
                            "ISBN", "Titulo"
                        };
                        int aux=0;
                        int aux2=0;
                        DefaultTableModel model = (DefaultTableModel) Respuesta.getModel();
                    for (Product nuevo1 : nuevo) {
                         a[aux][aux2]=nuevo1.isbn;
                         aux2++;
                         a[aux][aux2]=nuevo1.nombre;
                         aux++;
                         aux2=0;
                         }
                         model.setDataVector(a, b);
                         Respuesta.setModel(model);
                        }
                else{
                    JOptionPane.showMessageDialog(null, response.getMessage());
                }
        
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultar_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new consultar_categoria().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField Categoria;
    private javax.swing.JTextField Contra;
    javax.swing.JTable Respuesta;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
